[package]
name = "buckpal-application"
version = "0.1.0"
authors = ["Anthony Mittaz <sync@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rusty-money  = "0.3"
thiserror = "1.0.20"
anyhow = "1.0.31"
