name: Test & checks

on:
  push:
    branches: [master]
  pull_request:

env:
  DATABASE_URL: postgres://buckpal:buckpal@localhost/buckpal_test

jobs:
  ci:
    name: Test & checks
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: buckpal
          POSTGRES_PASSWORD: buckpal
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - id: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: Setup postgres and sqlx
        run: |
          sudo apt-get update
          sudo apt-get -y install libpq-dev
          cargo install sqlx-cli --git https://github.com/launchbadge/sqlx.git --no-default-features --features postgres

      - name: Create test db
        run: createdb -h localhost -U buckpal buckpal_test
        env:
          PGUSER: buckpal
          PGPASSWORD: buckpal

      - name: Migrate test db
        run: sqlx migrate run

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-${{ steps.rust-toolchain.outputs.rustc_hash }}-
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-${{ steps.rust-toolchain.outputs.rustc_hash }}-
            ${{ runner.os }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-${{ steps.rust-toolchain.outputs.rustc_hash }}-
            ${{ runner.os }}-cargo-build-target-

      - name: Build
        id: build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run tests
        uses: actions-rs/cargo@v1
        if: steps.build.outcome == 'success'
        with:
          command: test

      - name: Check rustfmt
        uses: actions-rs/cargo@v1
        if: steps.build.outcome == 'success'
        with:
          command: fmt
          args: --all -- --check
